/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VflacardPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  dailyLimit: 10,
  openaiBaseUrl: "https://api.openai.com/v1",
  openaiApiKey: "",
  openaiModel: "gpt-4o-mini"
};
var EBBINGHAUS_INTERVALS = [1, 2, 4, 7, 15, 30, 60];
var VflacardPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.flashcards = [];
    this.reviewProgress = { currentIndex: 0, date: "" };
  }
  async onload() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data == null ? void 0 : data.settings);
    this.flashcards = (data == null ? void 0 : data.flashcards) || [];
    this.reviewProgress = (data == null ? void 0 : data.reviewProgress) || { currentIndex: 0, date: "" };
    this.flashcards.forEach((card) => {
      if (!card.name) {
        card.name = card.content.slice(0, 10) + (card.content.length > 10 ? "..." : "");
      }
    });
    await this.advanceExpiredCards();
    this.addCommand({
      id: "create-flashcard",
      name: "\u5236\u6210\u5C55\u793A\u95EA\u5361",
      callback: () => this.createFlashcard()
    });
    this.addCommand({
      id: "create-multiple-flashcards",
      name: "\u4E3A\u9009\u533A\u521B\u5EFA\u591A\u4E2A\u95EA\u5361",
      callback: () => this.createMultipleFlashcards()
    });
    this.addCommand({
      id: "open-manager",
      name: "\u6253\u5F00\u95EA\u5361\u7BA1\u7406\u5668",
      callback: () => this.openView("vflacard-manager")
    });
    this.addCommand({
      id: "open-review",
      name: "\u6253\u5F00\u4ECA\u65E5\u590D\u4E60\u95EA\u5361",
      callback: () => this.openView("vflacard-review")
    });
    this.addRibbonIcon("layers", "\u5236\u6210\u5C55\u793A\u95EA\u5361", () => this.createFlashcard());
    this.addRibbonIcon("refresh-cw", "\u6253\u5F00\u4ECA\u65E5\u590D\u4E60\u95EA\u5361", () => this.openView("vflacard-review"));
    this.registerView("vflacard-manager", (leaf) => new ManagerView(leaf, this));
    this.registerView("vflacard-review", (leaf) => new ReviewView(leaf, this));
    this.addSettingTab(new VflacardSettingTab(this.app, this));
  }
  onunload() {
  }
  async saveAll() {
    await this.saveData({
      flashcards: this.flashcards,
      reviewProgress: this.reviewProgress,
      settings: this.settings
    });
  }
  // 刷新所有已打开的视图
  refreshViews() {
    const { workspace } = this.app;
    for (const leaf of workspace.getLeavesOfType("vflacard-manager")) {
      if (leaf.view instanceof ManagerView) {
        leaf.view.refresh();
      }
    }
    for (const leaf of workspace.getLeavesOfType("vflacard-review")) {
      if (leaf.view instanceof ReviewView) {
        leaf.view.refresh();
      }
    }
  }
  // 创建单张闪卡
  async createFlashcard() {
    var _a;
    const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
    if (!editor) {
      new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u7F16\u8F91\u5668\u5E76\u9009\u62E9\u6587\u672C");
      return;
    }
    const selection = editor.getSelection();
    if (!selection) {
      new import_obsidian.Notice("\u8BF7\u5148\u9009\u4E2D\u8981\u5236\u6210\u95EA\u5361\u7684\u6587\u672C");
      return;
    }
    const today = this.formatDate(/* @__PURE__ */ new Date());
    const assignedDate = this.assignDate(today);
    const card = {
      id: `card_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      name: selection.slice(0, 10) + (selection.length > 10 ? "..." : ""),
      content: selection,
      createTime: assignedDate,
      nextReviewTime: assignedDate,
      reviewCount: 0
    };
    this.flashcards.push(card);
    await this.saveAll();
    new import_obsidian.Notice(`\u95EA\u5361\u521B\u5EFA\u6210\u529F\uFF0C\u9996\u6B21\u590D\u4E60\u65E5\u671F\uFF1A${assignedDate}`);
    this.refreshViews();
  }
  // 批量创建闪卡
  async createMultipleFlashcards() {
    var _a, _b, _c, _d;
    const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
    if (!editor) {
      new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u7F16\u8F91\u5668\u5E76\u9009\u62E9\u6587\u672C");
      return;
    }
    const selection = editor.getSelection();
    if (!selection) {
      new import_obsidian.Notice("\u8BF7\u5148\u9009\u4E2D\u8981\u62C6\u5206\u4E3A\u591A\u4E2A\u95EA\u5361\u7684\u6587\u672C");
      return;
    }
    if (!this.settings.openaiBaseUrl || !this.settings.openaiApiKey || !this.settings.openaiModel) {
      new import_obsidian.Notice("\u8BF7\u5148\u5728\u63D2\u4EF6\u8BBE\u7F6E\u4E2D\u914D\u7F6E OpenAI \u517C\u5BB9 API\uFF08Base URL\u3001API Key\u3001\u6A21\u578B\u540D\uFF09");
      return;
    }
    try {
      const baseUrl = this.settings.openaiBaseUrl.replace(/\/+$/, "");
      const response = await fetch(`${baseUrl}/chat/completions`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${this.settings.openaiApiKey}`
        },
        body: JSON.stringify({
          model: this.settings.openaiModel,
          messages: [
            {
              role: "system",
              content: "\u5C06\u7ED9\u5B9A\u7684\u6587\u672C\u62C6\u5206\u4E3A\u591A\u4E2A\u72EC\u7ACB\u7684\u5B66\u4E60\u5361\u7247\u3002\u6BCF\u4E2A\u5361\u7247\u5FC5\u987B\u662F\u539F\u6587\u7684\u4E00\u4E2A\u8FDE\u7EED\u5B50\u4E32\uFF0C\u4E0D\u5F97\u4FEE\u6539\u3001\u6DFB\u52A0\u6216\u5220\u9664\u4EFB\u4F55\u5B57\u7B26\uFF08\u5305\u62EC\u7A7A\u683C\u548C\u6807\u70B9\uFF09\u3002\u8FD4\u56DE\u4E00\u4E2A JSON \u6570\u7EC4\uFF0C\u6570\u7EC4\u5143\u7D20\u4E3A\u5B57\u7B26\u4E32\uFF0C\u6BCF\u4E2A\u5B57\u7B26\u4E32\u5C31\u662F\u4E00\u4E2A\u5361\u7247\u5185\u5BB9\u3002\u4E0D\u8981\u6709\u4EFB\u4F55\u591A\u4F59\u89E3\u91CA\u3002"
            },
            { role: "user", content: selection }
          ],
          temperature: 0.1
        })
      });
      if (!response.ok) {
        throw new Error(`API \u8BF7\u6C42\u5931\u8D25: ${response.status} ${response.statusText}`);
      }
      const data = await response.json();
      const content = (_d = (_c = (_b = data.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.message) == null ? void 0 : _d.content;
      if (!content) throw new Error("AI \u54CD\u5E94\u4E2D\u6CA1\u6709\u5185\u5BB9");
      let cardContents = [];
      try {
        const parsed = JSON.parse(content);
        if (Array.isArray(parsed)) {
          cardContents = parsed.filter((x) => typeof x === "string");
        } else {
          throw new Error("\u54CD\u5E94\u4E0D\u662F JSON \u6570\u7EC4");
        }
      } catch (e) {
        const match = content.match(/```json\s*([\s\S]*?)\s*```/);
        if (match) {
          try {
            const parsed = JSON.parse(match[1]);
            if (Array.isArray(parsed)) cardContents = parsed.filter((x) => typeof x === "string");
            else throw new Error("\u4EE3\u7801\u5757\u4E2D\u7684\u5185\u5BB9\u4E0D\u662F JSON \u6570\u7EC4");
          } catch (e2) {
            throw new Error("JSON \u89E3\u6790\u5931\u8D25");
          }
        } else {
          throw new Error("\u65E0\u6CD5\u89E3\u6790 AI \u8FD4\u56DE\u7684\u5361\u7247\u5217\u8868");
        }
      }
      const validContents = [];
      for (const cardContent of cardContents) {
        if (cardContent.length > 0 && selection.includes(cardContent)) {
          validContents.push(cardContent);
        } else {
          console.warn("\u65E0\u6548\u5361\u7247\u7247\u6BB5\uFF08\u5DF2\u8DF3\u8FC7\uFF09:", cardContent);
        }
      }
      if (validContents.length === 0) {
        throw new Error("AI \u8FD4\u56DE\u7684\u6240\u6709\u5361\u7247\u7247\u6BB5\u5747\u4E0D\u662F\u539F\u6587\u7684\u8FDE\u7EED\u5B50\u4E32\uFF0C\u672A\u521B\u5EFA\u4EFB\u4F55\u5361\u7247");
      }
      for (const content2 of validContents) {
        const assignedDate = this.assignDate(this.formatDate(/* @__PURE__ */ new Date()));
        const card = {
          id: `card_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          name: content2.slice(0, 10) + (content2.length > 10 ? "..." : ""),
          content: content2,
          createTime: assignedDate,
          nextReviewTime: assignedDate,
          reviewCount: 0
        };
        this.flashcards.push(card);
      }
      await this.saveAll();
      this.refreshViews();
      new import_obsidian.Notice(`\u6210\u529F\u521B\u5EFA ${validContents.length} \u5F20\u95EA\u5361`);
    } catch (err) {
      new import_obsidian.Notice(`\u6279\u91CF\u521B\u5EFA\u5931\u8D25: ${err.message}`);
    }
  }
  assignDate(startDate) {
    const limit = this.settings.dailyLimit;
    const cursor = /* @__PURE__ */ new Date(startDate + "T00:00:00");
    while (true) {
      const dateStr = this.formatDate(cursor);
      const count = this.flashcards.filter((card) => card.createTime === dateStr).length;
      if (count < limit) {
        return dateStr;
      }
      cursor.setDate(cursor.getDate() + 1);
    }
  }
  async advanceExpiredCards() {
    const today = this.formatDate(/* @__PURE__ */ new Date());
    let changed = false;
    this.flashcards.forEach((card) => {
      while (card.nextReviewTime < today) {
        const interval = EBBINGHAUS_INTERVALS[Math.min(card.reviewCount, EBBINGHAUS_INTERVALS.length - 1)];
        const next = this.addDays(card.nextReviewTime, interval);
        card.nextReviewTime = next;
        card.reviewCount++;
        changed = true;
      }
    });
    if (changed) {
      await this.saveAll();
    }
  }
  advanceCard(card) {
    const today = this.formatDate(/* @__PURE__ */ new Date());
    while (card.nextReviewTime < today) {
      const interval = EBBINGHAUS_INTERVALS[Math.min(card.reviewCount, EBBINGHAUS_INTERVALS.length - 1)];
      const next = this.addDays(card.nextReviewTime, interval);
      card.nextReviewTime = next;
      card.reviewCount++;
    }
  }
  async openView(viewType) {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(viewType)[0];
    if (!leaf) {
      leaf = workspace.getLeaf(true);
      await leaf.setViewState({ type: viewType, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  addDays(dateStr, days) {
    const d = /* @__PURE__ */ new Date(dateStr + "T00:00:00");
    d.setDate(d.getDate() + days);
    return this.formatDate(d);
  }
  formatDate(date) {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, "0");
    const d = String(date.getDate()).padStart(2, "0");
    return `${y}-${m}-${d}`;
  }
  getTotalElapsedDays(reviewCount) {
    let total = 0;
    for (let i = 0; i < reviewCount; i++) {
      total += EBBINGHAUS_INTERVALS[Math.min(i, EBBINGHAUS_INTERVALS.length - 1)];
    }
    return total;
  }
};
var EditNameModal = class extends import_obsidian.Modal {
  constructor(app, plugin, card, onSave) {
    super(app);
    this.plugin = plugin;
    this.card = card;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u7F16\u8F91\u95EA\u5361\u540D\u79F0" });
    new import_obsidian.Setting(contentEl).setName("\u95EA\u5361\u540D\u79F0").addText((text) => {
      this.nameInput = text;
      text.setValue(this.card.name).setPlaceholder("\u8F93\u5165\u95EA\u5361\u540D\u79F0").onChange((value) => this.card.name = value);
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("\u4FDD\u5B58").setCta().onClick(async () => {
      await this.plugin.saveAll();
      if (this.onSave) this.onSave();
      this.close();
    })).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => this.close()));
  }
  onClose() {
    this.contentEl.empty();
  }
};
var EditCardModal = class extends import_obsidian.Modal {
  constructor(app, plugin, card, onSave) {
    super(app);
    this.plugin = plugin;
    this.card = card;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u7F16\u8F91\u95EA\u5361\u5185\u5BB9" });
    new import_obsidian.Setting(contentEl).setName("\u95EA\u5361\u5185\u5BB9").addTextArea((text) => {
      this.contentArea = text;
      text.setValue(this.card.content).setPlaceholder("\u8F93\u5165\u95EA\u5361\u5185\u5BB9").onChange((value) => this.card.content = value);
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("\u4FDD\u5B58").setCta().onClick(async () => {
      await this.plugin.saveAll();
      if (this.onSave) this.onSave();
      this.close();
    })).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => this.close()));
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ManagerView = class extends import_obsidian.ItemView {
  // 是否重新排序
  constructor(leaf, plugin) {
    super(leaf);
    this.sortedCards = [];
    this.searchQuery = "";
    this.needsSort = true;
    this.plugin = plugin;
  }
  getViewType() {
    return "vflacard-manager";
  }
  getDisplayText() {
    return "\u95EA\u5361\u7BA1\u7406\u5668";
  }
  getIcon() {
    return "layers";
  }
  async onOpen() {
    this.container = this.contentEl;
    this.needsSort = true;
    this.render();
  }
  async onClose() {
    this.container.empty();
  }
  // 刷新按钮调用
  refresh() {
    this.needsSort = true;
    this.render();
  }
  // 重新排序（按创建时间降序：最新在前）
  sortCards() {
    this.sortedCards = this.plugin.flashcards.slice().sort((a, b) => {
      if (a.createTime === b.createTime) {
        return b.id.localeCompare(a.id);
      }
      return b.createTime.localeCompare(a.createTime);
    });
    this.needsSort = false;
  }
  render() {
    if (this.needsSort) {
      this.sortCards();
    }
    this.container.empty();
    this.container.addClass("vflacard-container");
    const manager = this.container.createDiv({ cls: "vflacard-manager" });
    const toolbar = manager.createDiv({ cls: "vflacard-toolbar" });
    const searchInput = toolbar.createEl("input", {
      type: "text",
      cls: "vflacard-search-input",
      placeholder: "\u641C\u7D22\u95EA\u5361\u5185\u5BB9\u6216\u540D\u79F0...",
      attr: { "aria-label": "\u641C\u7D22\u95EA\u5361" }
    });
    searchInput.value = this.searchQuery;
    searchInput.addEventListener("input", (e) => {
      this.searchQuery = e.target.value;
      this.render();
    });
    const refreshBtn = toolbar.createEl("button", {
      cls: "vflacard-icon-btn vflacard-refresh-btn",
      attr: { "aria-label": "\u91CD\u65B0\u6392\u5E8F\u5E76\u5237\u65B0" }
    });
    (0, import_obsidian.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.onclick = () => {
      this.needsSort = true;
      this.render();
    };
    const filtered = this.sortedCards.filter((card) => {
      const q = this.searchQuery.toLowerCase();
      return card.name.toLowerCase().includes(q) || card.content.toLowerCase().includes(q);
    });
    if (filtered.length === 0) {
      manager.createEl("p", { text: "\u6682\u65E0\u95EA\u5361", cls: "vflacard-review-empty" });
      return;
    }
    for (const card of filtered) {
      this.createCardItem(manager, card);
    }
  }
  createCardItem(parent, card) {
    const item = parent.createDiv({ cls: "vflacard-card-item" });
    const info = item.createDiv({ cls: "vflacard-card-info" });
    const title = info.createDiv({ cls: "vflacard-card-title" });
    title.setText(card.name);
    const meta = info.createDiv({ cls: "vflacard-card-meta" });
    meta.createDiv({ text: `\u4E0B\u6B21\u590D\u4E60\uFF1A${card.nextReviewTime}` });
    meta.createDiv({ text: `\u521B\u5EFA\u65F6\u95F4\uFF1A${card.createTime}` });
    const actions = item.createDiv({ cls: "vflacard-card-actions" });
    const editNameBtn = actions.createEl("button", { cls: "vflacard-icon-btn", attr: { "aria-label": "\u7F16\u8F91\u540D\u79F0" } });
    (0, import_obsidian.setIcon)(editNameBtn, "text");
    editNameBtn.onclick = () => {
      new EditNameModal(this.app, this.plugin, card, () => this.plugin.refreshViews()).open();
    };
    const editBtn = actions.createEl("button", { cls: "vflacard-icon-btn", attr: { "aria-label": "\u7F16\u8F91\u5185\u5BB9" } });
    (0, import_obsidian.setIcon)(editBtn, "pencil");
    editBtn.onclick = () => {
      new EditCardModal(this.app, this.plugin, card, () => this.plugin.refreshViews()).open();
    };
    const deleteBtn = actions.createEl("button", { cls: "vflacard-icon-btn vflacard-icon-btn-delete", attr: { "aria-label": "\u5220\u9664" } });
    (0, import_obsidian.setIcon)(deleteBtn, "trash-2");
    deleteBtn.onclick = async () => {
      this.plugin.flashcards = this.plugin.flashcards.filter((c) => c.id !== card.id);
      await this.plugin.saveAll();
      this.plugin.refreshViews();
    };
    const prevBtn = actions.createEl("button", { cls: "vflacard-icon-btn", attr: { "aria-label": "\u521B\u5EFA\u65F6\u95F4\u5411\u524D\u63A8\u4E00\u5929" } });
    (0, import_obsidian.setIcon)(prevBtn, "arrow-left");
    prevBtn.onclick = async () => {
      card.createTime = this.plugin.addDays(card.createTime, -1);
      card.nextReviewTime = this.plugin.addDays(card.createTime, this.plugin.getTotalElapsedDays(card.reviewCount));
      this.plugin.advanceCard(card);
      await this.plugin.saveAll();
      this.render();
    };
    const nextBtn = actions.createEl("button", { cls: "vflacard-icon-btn", attr: { "aria-label": "\u521B\u5EFA\u65F6\u95F4\u5411\u540E\u63A8\u4E00\u5929" } });
    (0, import_obsidian.setIcon)(nextBtn, "arrow-right");
    nextBtn.onclick = async () => {
      card.createTime = this.plugin.addDays(card.createTime, 1);
      card.nextReviewTime = this.plugin.addDays(card.createTime, this.plugin.getTotalElapsedDays(card.reviewCount));
      this.plugin.advanceCard(card);
      await this.plugin.saveAll();
      this.render();
    };
  }
};
var ReviewView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentIndex = 0;
    this.reviewList = [];
    this.plugin = plugin;
  }
  getViewType() {
    return "vflacard-review";
  }
  getDisplayText() {
    return "\u4ECA\u65E5\u590D\u4E60\u95EA\u5361";
  }
  getIcon() {
    return "refresh-cw";
  }
  async onOpen() {
    this.container = this.contentEl;
    await this.plugin.advanceExpiredCards();
    this.render();
  }
  async onClose() {
    this.container.empty();
  }
  refresh() {
    this.render();
  }
  render() {
    this.container.empty();
    this.container.addClass("vflacard-container");
    const today = this.plugin.formatDate(/* @__PURE__ */ new Date());
    this.reviewList = this.plugin.flashcards.filter((card) => card.nextReviewTime === today);
    if (this.plugin.reviewProgress.date !== today) {
      this.plugin.reviewProgress = { currentIndex: 0, date: today };
    }
    const toolbar = this.container.createDiv({ cls: "vflacard-toolbar" });
    const refreshBtn = toolbar.createEl("button", {
      cls: "vflacard-icon-btn vflacard-refresh-btn",
      attr: { "aria-label": "\u5237\u65B0\u590D\u4E60\u5217\u8868" }
    });
    (0, import_obsidian.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.onclick = () => {
      this.render();
    };
    if (this.reviewList.length === 0) {
      this.container.createEl("p", { text: "\u4ECA\u65E5\u65E0\u5F85\u590D\u4E60\u5361\u7247", cls: "vflacard-review-empty" });
      return;
    }
    this.currentIndex = Math.min(this.plugin.reviewProgress.currentIndex, this.reviewList.length - 1);
    const reviewDiv = this.container.createDiv({ cls: "vflacard-review" });
    const cardDiv = reviewDiv.createDiv({ cls: "vflacard-review-card" });
    this.renderContent(cardDiv, this.reviewList[this.currentIndex].content);
    const nav = reviewDiv.createDiv({ cls: "vflacard-review-nav" });
    const prevBtn = nav.createEl("button", { cls: "vflacard-review-btn", attr: { "aria-label": "\u4E0A\u4E00\u5F20" } });
    (0, import_obsidian.setIcon)(prevBtn, "arrow-left");
    prevBtn.onclick = () => this.navigate(-1);
    const progress = nav.createDiv({ cls: "vflacard-review-progress" });
    progress.setText(`${this.currentIndex + 1} / ${this.reviewList.length}`);
    const nextBtn = nav.createEl("button", { cls: "vflacard-review-btn", attr: { "aria-label": "\u4E0B\u4E00\u5F20" } });
    (0, import_obsidian.setIcon)(nextBtn, "arrow-right");
    nextBtn.onclick = () => this.navigate(1);
  }
  async navigate(delta) {
    if (this.reviewList.length === 0) return;
    this.currentIndex = Math.max(0, Math.min(this.currentIndex + delta, this.reviewList.length - 1));
    this.plugin.reviewProgress.currentIndex = this.currentIndex;
    this.plugin.reviewProgress.date = this.plugin.formatDate(/* @__PURE__ */ new Date());
    await this.plugin.saveAll();
    this.render();
  }
  async renderContent(container, content) {
    container.empty();
    await import_obsidian.MarkdownRenderer.render(this.app, content, container, "", this);
  }
};
var VflacardSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u6BCF\u65E5\u65B0\u5361\u4E0A\u9650").setDesc("\u8BBE\u7F6E\u6BCF\u5929\u6700\u591A\u53EF\u5206\u914D\u7684\u95EA\u5361\u6570\u91CF\uFF0C\u8D85\u51FA\u540E\u987A\u5EF6\u81F3\u540E\u7EED\u65E5\u671F\u3002").addText((text) => text.setPlaceholder("10").setValue(String(this.plugin.settings.dailyLimit)).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num > 0) {
        this.plugin.settings.dailyLimit = num;
        await this.plugin.saveAll();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("OpenAI \u517C\u5BB9 API \u5730\u5740").setDesc("\u586B\u5199 Base URL\uFF0C\u4F8B\u5982 https://api.openai.com/v1").addText((text) => text.setPlaceholder("https://api.openai.com/v1").setValue(this.plugin.settings.openaiBaseUrl).onChange(async (value) => {
      this.plugin.settings.openaiBaseUrl = value.trim();
      await this.plugin.saveAll();
    }));
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("\u586B\u5199\u60A8\u7684 API \u5BC6\u94A5").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
      this.plugin.settings.openaiApiKey = value.trim();
      await this.plugin.saveAll();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u4F8B\u5982 gpt-4o-mini\u3001gpt-4o\u3001deepseek-chat \u7B49").addText((text) => text.setPlaceholder("gpt-4o-mini").setValue(this.plugin.settings.openaiModel).onChange(async (value) => {
      this.plugin.settings.openaiModel = value.trim();
      await this.plugin.saveAll();
    }));
  }
};
